name: StudioSpicer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#122232'
    - '#4a93f9'
    - '#fffeff'
    - '#a99685'
    - '#dac0a7'
  brandStrength: 0.6016043003182858
  lightness: 0.03607208118773997
  saturation: 0.3073359748814255
  rhythmicContrast: 0.8012843469623476
purpose: []
